[package]
name = "lumentix_sponsors"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
soroban-sdk = { version = "25.1.1", features = ["alloc"] }

[dev-dependencies]
soroban-sdk = { version = "25.1.1", features = ["alloc", "testutils"] }

[profile.release]
opt-level = "z"
overflow-checks = true
lto = true
codegen-units = 1
=======
=======
soroban-sdk = "25.1.1"

[dev-dependencies]
>>>>>>> 2a1a6e6 (feat(contract): implement on-chain sponsor tier management with Soroban)
soroban-sdk = { version = "25.1.1", features = ["testutils"] }
>>>>>>> 79a4553 (wip: add tests to contract)
